databases:
  - name: atomy
    plan: free
    databaseName: myatomy
    user: atomy

services:
  - type: web
    plan: free
    name: atomy
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn atomy.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: atomydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4